# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_rename_reps_workoutexercise_suggested_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='target_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                default=1
            ),
            preserve_default=False,
        ),
    ] 