# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def assign_users(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    User = apps.get_model('auth', 'User')
    user = User.objects.first()
    if user:
        Exercise.objects.update(user=user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_rename_reps_workoutexercise_suggested_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
        ),
        migrations.RunPython(assign_users),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
