# Generated by Django 5.0 on 2025-01-05 01:08

from django.db import migrations

def assign_exercises_to_first_user(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    User = apps.get_model('auth', 'User')
    
    # Get the first user or create a default one if none exists
    default_user = User.objects.first()
    if not default_user:
        default_user = User.objects.create_user(
            username='admin',
            email='admin@example.com',
            password='adminpassword'
        )
    
    # Assign all exercises without a user to the default user
    Exercise.objects.filter(user__isnull=True).update(user=default_user)

def reverse_exercise_user_assignment(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    Exercise.objects.all().update(user=None)

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_user'),
    ]

    operations = [
        migrations.RunPython(
            assign_exercises_to_first_user,
            reverse_exercise_user_assignment
        ),
    ]
