# Generated by Django 5.0

from django.db import migrations

def fix_exercise_user_assignments(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    WorkoutExercise = apps.get_model('workouts', 'WorkoutExercise')
    
    # For each workout exercise
    for workout_exercise in WorkoutExercise.objects.all():
        # Get the workout's user and assign it to the exercise if needed
        exercise = workout_exercise.exercise
        workout_user = workout_exercise.workout.user
        if exercise.user != workout_user:
            # Create a new exercise for this user if it doesn't exist
            new_exercise, created = Exercise.objects.get_or_create(
                name=exercise.name,
                target_muscle=exercise.target_muscle,
                description=exercise.description,
                user=workout_user
            )
            if created:
                # Update the workout exercise to point to the new exercise
                workout_exercise.exercise = new_exercise
                workout_exercise.save()

def reverse_exercise_assignments(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_assign_exercises_to_users'),
    ]

    operations = [
        migrations.RunPython(
            fix_exercise_user_assignments,
            reverse_exercise_assignments
        ),
    ] 