# Generated by Django 5.0 on 2025-01-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_fix_exercise_user_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='updated_at',
        ),
    ]
